// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pelicanq/v1/admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pelicanq_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_admin_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pelicanq_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_pelicanq_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_admin_proto_rawDescGZIP(), []int{2}
}

type ClusterStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SelfId          uint64                 `protobuf:"varint,1,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	IsLeader        bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	CurrentLeaderId *uint64                `protobuf:"varint,3,opt,name=current_leader_id,json=currentLeaderId,proto3,oneof" json:"current_leader_id,omitempty"`
	Members         []*ClusterMember       `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_pelicanq_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterStatusResponse) GetSelfId() uint64 {
	if x != nil {
		return x.SelfId
	}
	return 0
}

func (x *ClusterStatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *ClusterStatusResponse) GetCurrentLeaderId() uint64 {
	if x != nil && x.CurrentLeaderId != nil {
		return *x.CurrentLeaderId
	}
	return 0
}

func (x *ClusterStatusResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ClusterMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_pelicanq_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterMember) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *ClusterMember) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

var File_pelicanq_v1_admin_proto protoreflect.FileDescriptor

const file_pelicanq_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x17pelicanq/v1/admin.proto\x12\vpelicanq.v1\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x16\n" +
	"\x14ClusterStatusRequest\"\xca\x01\n" +
	"\x15ClusterStatusResponse\x12\x17\n" +
	"\aself_id\x18\x01 \x01(\x04R\x06selfId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12/\n" +
	"\x11current_leader_id\x18\x03 \x01(\x04H\x00R\x0fcurrentLeaderId\x88\x01\x01\x124\n" +
	"\amembers\x18\x04 \x03(\v2\x1a.pelicanq.v1.ClusterMemberR\amembersB\x14\n" +
	"\x12_current_leader_id\"]\n" +
	"\rClusterMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1f\n" +
	"\vclient_addr\x18\x03 \x01(\tR\n" +
	"clientAddr2\xa9\x01\n" +
	"\fAdminService\x12A\n" +
	"\x06Health\x12\x1a.pelicanq.v1.HealthRequest\x1a\x1b.pelicanq.v1.HealthResponse\x12V\n" +
	"\rClusterStatus\x12!.pelicanq.v1.ClusterStatusRequest\x1a\".pelicanq.v1.ClusterStatusResponseB\x10Z\x0epelicanq/pb/v1b\x06proto3"

var (
	file_pelicanq_v1_admin_proto_rawDescOnce sync.Once
	file_pelicanq_v1_admin_proto_rawDescData []byte
)

func file_pelicanq_v1_admin_proto_rawDescGZIP() []byte {
	file_pelicanq_v1_admin_proto_rawDescOnce.Do(func() {
		file_pelicanq_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pelicanq_v1_admin_proto_rawDesc), len(file_pelicanq_v1_admin_proto_rawDesc)))
	})
	return file_pelicanq_v1_admin_proto_rawDescData
}

var file_pelicanq_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pelicanq_v1_admin_proto_goTypes = []any{
	(*HealthRequest)(nil),         // 0: pelicanq.v1.HealthRequest
	(*HealthResponse)(nil),        // 1: pelicanq.v1.HealthResponse
	(*ClusterStatusRequest)(nil),  // 2: pelicanq.v1.ClusterStatusRequest
	(*ClusterStatusResponse)(nil), // 3: pelicanq.v1.ClusterStatusResponse
	(*ClusterMember)(nil),         // 4: pelicanq.v1.ClusterMember
}
var file_pelicanq_v1_admin_proto_depIdxs = []int32{
	4, // 0: pelicanq.v1.ClusterStatusResponse.members:type_name -> pelicanq.v1.ClusterMember
	0, // 1: pelicanq.v1.AdminService.Health:input_type -> pelicanq.v1.HealthRequest
	2, // 2: pelicanq.v1.AdminService.ClusterStatus:input_type -> pelicanq.v1.ClusterStatusRequest
	1, // 3: pelicanq.v1.AdminService.Health:output_type -> pelicanq.v1.HealthResponse
	3, // 4: pelicanq.v1.AdminService.ClusterStatus:output_type -> pelicanq.v1.ClusterStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pelicanq_v1_admin_proto_init() }
func file_pelicanq_v1_admin_proto_init() {
	if File_pelicanq_v1_admin_proto != nil {
		return
	}
	file_pelicanq_v1_admin_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pelicanq_v1_admin_proto_rawDesc), len(file_pelicanq_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pelicanq_v1_admin_proto_goTypes,
		DependencyIndexes: file_pelicanq_v1_admin_proto_depIdxs,
		MessageInfos:      file_pelicanq_v1_admin_proto_msgTypes,
	}.Build()
	File_pelicanq_v1_admin_proto = out.File
	file_pelicanq_v1_admin_proto_goTypes = nil
	file_pelicanq_v1_admin_proto_depIdxs = nil
}
