// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pelicanq/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload          []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers          map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Priority         uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	DeliverAt        *int64                 `protobuf:"varint,6,opt,name=deliver_at,json=deliverAt,proto3,oneof" json:"deliver_at,omitempty"`
	DedupKey         *string                `protobuf:"bytes,7,opt,name=dedup_key,json=dedupKey,proto3,oneof" json:"dedup_key,omitempty"`
	DeliveryAttempts uint32                 `protobuf:"varint,8,opt,name=delivery_attempts,json=deliveryAttempts,proto3" json:"delivery_attempts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pelicanq_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetDeliverAt() int64 {
	if x != nil && x.DeliverAt != nil {
		return *x.DeliverAt
	}
	return 0
}

func (x *Message) GetDedupKey() string {
	if x != nil && x.DedupKey != nil {
		return *x.DedupKey
	}
	return ""
}

func (x *Message) GetDeliveryAttempts() uint32 {
	if x != nil {
		return x.DeliveryAttempts
	}
	return 0
}

type ConsumedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryTag   uint64                 `protobuf:"varint,1,opt,name=delivery_tag,json=deliveryTag,proto3" json:"delivery_tag,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumedMessage) Reset() {
	*x = ConsumedMessage{}
	mi := &file_pelicanq_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumedMessage) ProtoMessage() {}

func (x *ConsumedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumedMessage.ProtoReflect.Descriptor instead.
func (*ConsumedMessage) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumedMessage) GetDeliveryTag() uint64 {
	if x != nil {
		return x.DeliveryTag
	}
	return 0
}

func (x *ConsumedMessage) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_pelicanq_v1_message_proto protoreflect.FileDescriptor

const file_pelicanq_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x19pelicanq/v1/message.proto\x12\vpelicanq.v1\"\xf6\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12;\n" +
	"\aheaders\x18\x03 \x03(\v2!.pelicanq.v1.Message.HeadersEntryR\aheaders\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x12\"\n" +
	"\n" +
	"deliver_at\x18\x06 \x01(\x03H\x00R\tdeliverAt\x88\x01\x01\x12 \n" +
	"\tdedup_key\x18\a \x01(\tH\x01R\bdedupKey\x88\x01\x01\x12+\n" +
	"\x11delivery_attempts\x18\b \x01(\rR\x10deliveryAttempts\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_deliver_atB\f\n" +
	"\n" +
	"_dedup_key\"d\n" +
	"\x0fConsumedMessage\x12!\n" +
	"\fdelivery_tag\x18\x01 \x01(\x04R\vdeliveryTag\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x14.pelicanq.v1.MessageR\amessageB\x10Z\x0epelicanq/pb/v1b\x06proto3"

var (
	file_pelicanq_v1_message_proto_rawDescOnce sync.Once
	file_pelicanq_v1_message_proto_rawDescData []byte
)

func file_pelicanq_v1_message_proto_rawDescGZIP() []byte {
	file_pelicanq_v1_message_proto_rawDescOnce.Do(func() {
		file_pelicanq_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pelicanq_v1_message_proto_rawDesc), len(file_pelicanq_v1_message_proto_rawDesc)))
	})
	return file_pelicanq_v1_message_proto_rawDescData
}

var file_pelicanq_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pelicanq_v1_message_proto_goTypes = []any{
	(*Message)(nil),         // 0: pelicanq.v1.Message
	(*ConsumedMessage)(nil), // 1: pelicanq.v1.ConsumedMessage
	nil,                     // 2: pelicanq.v1.Message.HeadersEntry
}
var file_pelicanq_v1_message_proto_depIdxs = []int32{
	2, // 0: pelicanq.v1.Message.headers:type_name -> pelicanq.v1.Message.HeadersEntry
	0, // 1: pelicanq.v1.ConsumedMessage.message:type_name -> pelicanq.v1.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pelicanq_v1_message_proto_init() }
func file_pelicanq_v1_message_proto_init() {
	if File_pelicanq_v1_message_proto != nil {
		return
	}
	file_pelicanq_v1_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pelicanq_v1_message_proto_rawDesc), len(file_pelicanq_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pelicanq_v1_message_proto_goTypes,
		DependencyIndexes: file_pelicanq_v1_message_proto_depIdxs,
		MessageInfos:      file_pelicanq_v1_message_proto_msgTypes,
	}.Build()
	File_pelicanq_v1_message_proto = out.File
	file_pelicanq_v1_message_proto_goTypes = nil
	file_pelicanq_v1_message_proto_depIdxs = nil
}
