// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pelicanq/v1/queue.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeclareQueueRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxAgeSecs          *uint64                `protobuf:"varint,2,opt,name=max_age_secs,json=maxAgeSecs,proto3,oneof" json:"max_age_secs,omitempty"`
	MaxMessages         *uint64                `protobuf:"varint,3,opt,name=max_messages,json=maxMessages,proto3,oneof" json:"max_messages,omitempty"`
	MaxDeliveryAttempts *uint32                `protobuf:"varint,4,opt,name=max_delivery_attempts,json=maxDeliveryAttempts,proto3,oneof" json:"max_delivery_attempts,omitempty"`
	DeadLetterQueue     *string                `protobuf:"bytes,5,opt,name=dead_letter_queue,json=deadLetterQueue,proto3,oneof" json:"dead_letter_queue,omitempty"`
	DedupWindowSecs     *uint64                `protobuf:"varint,6,opt,name=dedup_window_secs,json=dedupWindowSecs,proto3,oneof" json:"dedup_window_secs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeclareQueueRequest) Reset() {
	*x = DeclareQueueRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareQueueRequest) ProtoMessage() {}

func (x *DeclareQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareQueueRequest.ProtoReflect.Descriptor instead.
func (*DeclareQueueRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *DeclareQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeclareQueueRequest) GetMaxAgeSecs() uint64 {
	if x != nil && x.MaxAgeSecs != nil {
		return *x.MaxAgeSecs
	}
	return 0
}

func (x *DeclareQueueRequest) GetMaxMessages() uint64 {
	if x != nil && x.MaxMessages != nil {
		return *x.MaxMessages
	}
	return 0
}

func (x *DeclareQueueRequest) GetMaxDeliveryAttempts() uint32 {
	if x != nil && x.MaxDeliveryAttempts != nil {
		return *x.MaxDeliveryAttempts
	}
	return 0
}

func (x *DeclareQueueRequest) GetDeadLetterQueue() string {
	if x != nil && x.DeadLetterQueue != nil {
		return *x.DeadLetterQueue
	}
	return ""
}

func (x *DeclareQueueRequest) GetDedupWindowSecs() uint64 {
	if x != nil && x.DedupWindowSecs != nil {
		return *x.DedupWindowSecs
	}
	return 0
}

type DeclareQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareQueueResponse) Reset() {
	*x = DeclareQueueResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareQueueResponse) ProtoMessage() {}

func (x *DeclareQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareQueueResponse.ProtoReflect.Descriptor instead.
func (*DeclareQueueResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *DeclareQueueResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{2}
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

type QueueInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Depth          uint64                 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	ScheduledDepth uint64                 `protobuf:"varint,3,opt,name=scheduled_depth,json=scheduledDepth,proto3" json:"scheduled_depth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetDepth() uint64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *QueueInfo) GetScheduledDepth() uint64 {
	if x != nil {
		return x.ScheduledDepth
	}
	return 0
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{5}
}

func (x *PublishRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PublishRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{6}
}

func (x *PublishResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{7}
}

func (x *PublishBatchRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PublishBatchRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PublishResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{8}
}

func (x *PublishBatchResponse) GetResults() []*PublishResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ConsumedMessage       `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeResponse) GetMessage() *ConsumedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ConsumeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Max           uint32                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeBatchRequest) Reset() {
	*x = ConsumeBatchRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeBatchRequest) ProtoMessage() {}

func (x *ConsumeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeBatchRequest.ProtoReflect.Descriptor instead.
func (*ConsumeBatchRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{11}
}

func (x *ConsumeBatchRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ConsumeBatchRequest) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ConsumeBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsumedMessage     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeBatchResponse) Reset() {
	*x = ConsumeBatchResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeBatchResponse) ProtoMessage() {}

func (x *ConsumeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeBatchResponse.ProtoReflect.Descriptor instead.
func (*ConsumeBatchResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeBatchResponse) GetMessages() []*ConsumedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ConsumeStreamAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryTag     *uint64                `protobuf:"varint,1,opt,name=delivery_tag,json=deliveryTag,proto3,oneof" json:"delivery_tag,omitempty"`
	NackDeliveryTag *uint64                `protobuf:"varint,2,opt,name=nack_delivery_tag,json=nackDeliveryTag,proto3,oneof" json:"nack_delivery_tag,omitempty"`
	Queue           *string                `protobuf:"bytes,3,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsumeStreamAck) Reset() {
	*x = ConsumeStreamAck{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeStreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeStreamAck) ProtoMessage() {}

func (x *ConsumeStreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeStreamAck.ProtoReflect.Descriptor instead.
func (*ConsumeStreamAck) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{13}
}

func (x *ConsumeStreamAck) GetDeliveryTag() uint64 {
	if x != nil && x.DeliveryTag != nil {
		return *x.DeliveryTag
	}
	return 0
}

func (x *ConsumeStreamAck) GetNackDeliveryTag() uint64 {
	if x != nil && x.NackDeliveryTag != nil {
		return *x.NackDeliveryTag
	}
	return 0
}

func (x *ConsumeStreamAck) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	DeliveryTag   uint64                 `protobuf:"varint,2,opt,name=delivery_tag,json=deliveryTag,proto3" json:"delivery_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{14}
}

func (x *AckRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *AckRequest) GetDeliveryTag() uint64 {
	if x != nil {
		return x.DeliveryTag
	}
	return 0
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{15}
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	DeliveryTag   uint64                 `protobuf:"varint,2,opt,name=delivery_tag,json=deliveryTag,proto3" json:"delivery_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{16}
}

func (x *NackRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *NackRequest) GetDeliveryTag() uint64 {
	if x != nil {
		return x.DeliveryTag
	}
	return 0
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_pelicanq_v1_queue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pelicanq_v1_queue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_pelicanq_v1_queue_proto_rawDescGZIP(), []int{17}
}

var File_pelicanq_v1_queue_proto protoreflect.FileDescriptor

const file_pelicanq_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x17pelicanq/v1/queue.proto\x12\vpelicanq.v1\x1a\x19pelicanq/v1/message.proto\"\xfb\x02\n" +
	"\x13DeclareQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\fmax_age_secs\x18\x02 \x01(\x04H\x00R\n" +
	"maxAgeSecs\x88\x01\x01\x12&\n" +
	"\fmax_messages\x18\x03 \x01(\x04H\x01R\vmaxMessages\x88\x01\x01\x127\n" +
	"\x15max_delivery_attempts\x18\x04 \x01(\rH\x02R\x13maxDeliveryAttempts\x88\x01\x01\x12/\n" +
	"\x11dead_letter_queue\x18\x05 \x01(\tH\x03R\x0fdeadLetterQueue\x88\x01\x01\x12/\n" +
	"\x11dedup_window_secs\x18\x06 \x01(\x04H\x04R\x0fdedupWindowSecs\x88\x01\x01B\x0f\n" +
	"\r_max_age_secsB\x0f\n" +
	"\r_max_messagesB\x18\n" +
	"\x16_max_delivery_attemptsB\x14\n" +
	"\x12_dead_letter_queueB\x14\n" +
	"\x12_dedup_window_secs\"0\n" +
	"\x14DeclareQueueResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"\x13\n" +
	"\x11ListQueuesRequest\"D\n" +
	"\x12ListQueuesResponse\x12.\n" +
	"\x06queues\x18\x01 \x03(\v2\x16.pelicanq.v1.QueueInfoR\x06queues\"^\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x04R\x05depth\x12'\n" +
	"\x0fscheduled_depth\x18\x03 \x01(\x04R\x0escheduledDepth\"V\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x14.pelicanq.v1.MessageR\amessage\"E\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"]\n" +
	"\x13PublishBatchRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.pelicanq.v1.MessageR\bmessages\"N\n" +
	"\x14PublishBatchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.pelicanq.v1.PublishResponseR\aresults\"&\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"Z\n" +
	"\x0fConsumeResponse\x12;\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.pelicanq.v1.ConsumedMessageH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"=\n" +
	"\x13ConsumeBatchRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\"P\n" +
	"\x14ConsumeBatchResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.pelicanq.v1.ConsumedMessageR\bmessages\"\xb7\x01\n" +
	"\x10ConsumeStreamAck\x12&\n" +
	"\fdelivery_tag\x18\x01 \x01(\x04H\x00R\vdeliveryTag\x88\x01\x01\x12/\n" +
	"\x11nack_delivery_tag\x18\x02 \x01(\x04H\x01R\x0fnackDeliveryTag\x88\x01\x01\x12\x19\n" +
	"\x05queue\x18\x03 \x01(\tH\x02R\x05queue\x88\x01\x01B\x0f\n" +
	"\r_delivery_tagB\x14\n" +
	"\x12_nack_delivery_tagB\b\n" +
	"\x06_queue\"E\n" +
	"\n" +
	"AckRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fdelivery_tag\x18\x02 \x01(\x04R\vdeliveryTag\"\r\n" +
	"\vAckResponse\"F\n" +
	"\vNackRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fdelivery_tag\x18\x02 \x01(\x04R\vdeliveryTag\"\x0e\n" +
	"\fNackResponse2\xb1\x05\n" +
	"\fQueueService\x12S\n" +
	"\fDeclareQueue\x12 .pelicanq.v1.DeclareQueueRequest\x1a!.pelicanq.v1.DeclareQueueResponse\x12M\n" +
	"\n" +
	"ListQueues\x12\x1e.pelicanq.v1.ListQueuesRequest\x1a\x1f.pelicanq.v1.ListQueuesResponse\x12D\n" +
	"\aPublish\x12\x1b.pelicanq.v1.PublishRequest\x1a\x1c.pelicanq.v1.PublishResponse\x12S\n" +
	"\fPublishBatch\x12 .pelicanq.v1.PublishBatchRequest\x1a!.pelicanq.v1.PublishBatchResponse\x12D\n" +
	"\aConsume\x12\x1b.pelicanq.v1.ConsumeRequest\x1a\x1c.pelicanq.v1.ConsumeResponse\x12S\n" +
	"\fConsumeBatch\x12 .pelicanq.v1.ConsumeBatchRequest\x1a!.pelicanq.v1.ConsumeBatchResponse\x12P\n" +
	"\rConsumeStream\x12\x1d.pelicanq.v1.ConsumeStreamAck\x1a\x1c.pelicanq.v1.ConsumedMessage(\x010\x01\x128\n" +
	"\x03Ack\x12\x17.pelicanq.v1.AckRequest\x1a\x18.pelicanq.v1.AckResponse\x12;\n" +
	"\x04Nack\x12\x18.pelicanq.v1.NackRequest\x1a\x19.pelicanq.v1.NackResponseB\x10Z\x0epelicanq/pb/v1b\x06proto3"

var (
	file_pelicanq_v1_queue_proto_rawDescOnce sync.Once
	file_pelicanq_v1_queue_proto_rawDescData []byte
)

func file_pelicanq_v1_queue_proto_rawDescGZIP() []byte {
	file_pelicanq_v1_queue_proto_rawDescOnce.Do(func() {
		file_pelicanq_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pelicanq_v1_queue_proto_rawDesc), len(file_pelicanq_v1_queue_proto_rawDesc)))
	})
	return file_pelicanq_v1_queue_proto_rawDescData
}

var file_pelicanq_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pelicanq_v1_queue_proto_goTypes = []any{
	(*DeclareQueueRequest)(nil),  // 0: pelicanq.v1.DeclareQueueRequest
	(*DeclareQueueResponse)(nil), // 1: pelicanq.v1.DeclareQueueResponse
	(*ListQueuesRequest)(nil),    // 2: pelicanq.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),   // 3: pelicanq.v1.ListQueuesResponse
	(*QueueInfo)(nil),            // 4: pelicanq.v1.QueueInfo
	(*PublishRequest)(nil),       // 5: pelicanq.v1.PublishRequest
	(*PublishResponse)(nil),      // 6: pelicanq.v1.PublishResponse
	(*PublishBatchRequest)(nil),  // 7: pelicanq.v1.PublishBatchRequest
	(*PublishBatchResponse)(nil), // 8: pelicanq.v1.PublishBatchResponse
	(*ConsumeRequest)(nil),       // 9: pelicanq.v1.ConsumeRequest
	(*ConsumeResponse)(nil),      // 10: pelicanq.v1.ConsumeResponse
	(*ConsumeBatchRequest)(nil),  // 11: pelicanq.v1.ConsumeBatchRequest
	(*ConsumeBatchResponse)(nil), // 12: pelicanq.v1.ConsumeBatchResponse
	(*ConsumeStreamAck)(nil),     // 13: pelicanq.v1.ConsumeStreamAck
	(*AckRequest)(nil),           // 14: pelicanq.v1.AckRequest
	(*AckResponse)(nil),          // 15: pelicanq.v1.AckResponse
	(*NackRequest)(nil),          // 16: pelicanq.v1.NackRequest
	(*NackResponse)(nil),         // 17: pelicanq.v1.NackResponse
	(*Message)(nil),              // 18: pelicanq.v1.Message
	(*ConsumedMessage)(nil),      // 19: pelicanq.v1.ConsumedMessage
}
var file_pelicanq_v1_queue_proto_depIdxs = []int32{
	4,  // 0: pelicanq.v1.ListQueuesResponse.queues:type_name -> pelicanq.v1.QueueInfo
	18, // 1: pelicanq.v1.PublishRequest.message:type_name -> pelicanq.v1.Message
	18, // 2: pelicanq.v1.PublishBatchRequest.messages:type_name -> pelicanq.v1.Message
	6,  // 3: pelicanq.v1.PublishBatchResponse.results:type_name -> pelicanq.v1.PublishResponse
	19, // 4: pelicanq.v1.ConsumeResponse.message:type_name -> pelicanq.v1.ConsumedMessage
	19, // 5: pelicanq.v1.ConsumeBatchResponse.messages:type_name -> pelicanq.v1.ConsumedMessage
	0,  // 6: pelicanq.v1.QueueService.DeclareQueue:input_type -> pelicanq.v1.DeclareQueueRequest
	2,  // 7: pelicanq.v1.QueueService.ListQueues:input_type -> pelicanq.v1.ListQueuesRequest
	5,  // 8: pelicanq.v1.QueueService.Publish:input_type -> pelicanq.v1.PublishRequest
	7,  // 9: pelicanq.v1.QueueService.PublishBatch:input_type -> pelicanq.v1.PublishBatchRequest
	9,  // 10: pelicanq.v1.QueueService.Consume:input_type -> pelicanq.v1.ConsumeRequest
	11, // 11: pelicanq.v1.QueueService.ConsumeBatch:input_type -> pelicanq.v1.ConsumeBatchRequest
	13, // 12: pelicanq.v1.QueueService.ConsumeStream:input_type -> pelicanq.v1.ConsumeStreamAck
	14, // 13: pelicanq.v1.QueueService.Ack:input_type -> pelicanq.v1.AckRequest
	16, // 14: pelicanq.v1.QueueService.Nack:input_type -> pelicanq.v1.NackRequest
	1,  // 15: pelicanq.v1.QueueService.DeclareQueue:output_type -> pelicanq.v1.DeclareQueueResponse
	3,  // 16: pelicanq.v1.QueueService.ListQueues:output_type -> pelicanq.v1.ListQueuesResponse
	6,  // 17: pelicanq.v1.QueueService.Publish:output_type -> pelicanq.v1.PublishResponse
	8,  // 18: pelicanq.v1.QueueService.PublishBatch:output_type -> pelicanq.v1.PublishBatchResponse
	10, // 19: pelicanq.v1.QueueService.Consume:output_type -> pelicanq.v1.ConsumeResponse
	12, // 20: pelicanq.v1.QueueService.ConsumeBatch:output_type -> pelicanq.v1.ConsumeBatchResponse
	19, // 21: pelicanq.v1.QueueService.ConsumeStream:output_type -> pelicanq.v1.ConsumedMessage
	15, // 22: pelicanq.v1.QueueService.Ack:output_type -> pelicanq.v1.AckResponse
	17, // 23: pelicanq.v1.QueueService.Nack:output_type -> pelicanq.v1.NackResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pelicanq_v1_queue_proto_init() }
func file_pelicanq_v1_queue_proto_init() {
	if File_pelicanq_v1_queue_proto != nil {
		return
	}
	file_pelicanq_v1_message_proto_init()
	file_pelicanq_v1_queue_proto_msgTypes[0].OneofWrappers = []any{}
	file_pelicanq_v1_queue_proto_msgTypes[10].OneofWrappers = []any{}
	file_pelicanq_v1_queue_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pelicanq_v1_queue_proto_rawDesc), len(file_pelicanq_v1_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pelicanq_v1_queue_proto_goTypes,
		DependencyIndexes: file_pelicanq_v1_queue_proto_depIdxs,
		MessageInfos:      file_pelicanq_v1_queue_proto_msgTypes,
	}.Build()
	File_pelicanq_v1_queue_proto = out.File
	file_pelicanq_v1_queue_proto_goTypes = nil
	file_pelicanq_v1_queue_proto_depIdxs = nil
}
