# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pelicanq/v1/admin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pelicanq/v1/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pelicanq/v1/admin.proto\x12\x0bpelicanq.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x16\n\x14\x43lusterStatusRequest\"\x9e\x01\n\x15\x43lusterStatusResponse\x12\x0f\n\x07self_id\x18\x01 \x01(\x04\x12\x11\n\tis_leader\x18\x02 \x01(\x08\x12\x1e\n\x11\x63urrent_leader_id\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12+\n\x07members\x18\x04 \x03(\x0b\x32\x1a.pelicanq.v1.ClusterMemberB\x14\n\x12_current_leader_id\"C\n\rClusterMember\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\traft_addr\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_addr\x18\x03 \x01(\t2\xa9\x01\n\x0c\x41\x64minService\x12\x41\n\x06Health\x12\x1a.pelicanq.v1.HealthRequest\x1a\x1b.pelicanq.v1.HealthResponse\x12V\n\rClusterStatus\x12!.pelicanq.v1.ClusterStatusRequest\x1a\".pelicanq.v1.ClusterStatusResponseB\x10Z\x0epelicanq/pb/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pelicanq.v1.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016pelicanq/pb/v1'
  _globals['_HEALTHREQUEST']._serialized_start=40
  _globals['_HEALTHREQUEST']._serialized_end=55
  _globals['_HEALTHRESPONSE']._serialized_start=57
  _globals['_HEALTHRESPONSE']._serialized_end=89
  _globals['_CLUSTERSTATUSREQUEST']._serialized_start=91
  _globals['_CLUSTERSTATUSREQUEST']._serialized_end=113
  _globals['_CLUSTERSTATUSRESPONSE']._serialized_start=116
  _globals['_CLUSTERSTATUSRESPONSE']._serialized_end=274
  _globals['_CLUSTERMEMBER']._serialized_start=276
  _globals['_CLUSTERMEMBER']._serialized_end=343
  _globals['_ADMINSERVICE']._serialized_start=346
  _globals['_ADMINSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
