# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pelicanq.v1 import admin_pb2 as pelicanq_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pelicanq/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/pelicanq.v1.AdminService/Health',
                request_serializer=pelicanq_dot_v1_dot_admin__pb2.HealthRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_admin__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ClusterStatus = channel.unary_unary(
                '/pelicanq.v1.AdminService/ClusterStatus',
                request_serializer=pelicanq_dot_v1_dot_admin__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_admin__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=pelicanq_dot_v1_dot_admin__pb2.HealthRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_admin__pb2.HealthResponse.SerializeToString,
            ),
            'ClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterStatus,
                    request_deserializer=pelicanq_dot_v1_dot_admin__pb2.ClusterStatusRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_admin__pb2.ClusterStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pelicanq.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pelicanq.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.AdminService/Health',
            pelicanq_dot_v1_dot_admin__pb2.HealthRequest.SerializeToString,
            pelicanq_dot_v1_dot_admin__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.AdminService/ClusterStatus',
            pelicanq_dot_v1_dot_admin__pb2.ClusterStatusRequest.SerializeToString,
            pelicanq_dot_v1_dot_admin__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
