# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pelicanq/v1/message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pelicanq/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pelicanq/v1/message.proto\x12\x0bpelicanq.v1\"\x98\x02\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x32\n\x07headers\x18\x03 \x03(\x0b\x32!.pelicanq.v1.Message.HeadersEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08priority\x18\x05 \x01(\r\x12\x17\n\ndeliver_at\x18\x06 \x01(\x03H\x00\x88\x01\x01\x12\x16\n\tdedup_key\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x11\x64\x65livery_attempts\x18\x08 \x01(\r\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_deliver_atB\x0c\n\n_dedup_key\"N\n\x0f\x43onsumedMessage\x12\x14\n\x0c\x64\x65livery_tag\x18\x01 \x01(\x04\x12%\n\x07message\x18\x02 \x01(\x0b\x32\x14.pelicanq.v1.MessageB\x10Z\x0epelicanq/pb/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pelicanq.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016pelicanq/pb/v1'
  _globals['_MESSAGE_HEADERSENTRY']._loaded_options = None
  _globals['_MESSAGE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=43
  _globals['_MESSAGE']._serialized_end=323
  _globals['_MESSAGE_HEADERSENTRY']._serialized_start=248
  _globals['_MESSAGE_HEADERSENTRY']._serialized_end=294
  _globals['_CONSUMEDMESSAGE']._serialized_start=325
  _globals['_CONSUMEDMESSAGE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
