# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pelicanq.v1 import message_pb2 as pelicanq_dot_v1_dot_message__pb2
from pelicanq.v1 import queue_pb2 as pelicanq_dot_v1_dot_queue__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pelicanq/v1/queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeclareQueue = channel.unary_unary(
                '/pelicanq.v1.QueueService/DeclareQueue',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.DeclareQueueRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.DeclareQueueResponse.FromString,
                _registered_method=True)
        self.ListQueues = channel.unary_unary(
                '/pelicanq.v1.QueueService/ListQueues',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.ListQueuesRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.ListQueuesResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/pelicanq.v1.QueueService/Publish',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.PublishRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.PublishBatch = channel.unary_unary(
                '/pelicanq.v1.QueueService/PublishBatch',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.PublishBatchRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.PublishBatchResponse.FromString,
                _registered_method=True)
        self.Consume = channel.unary_unary(
                '/pelicanq.v1.QueueService/Consume',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeResponse.FromString,
                _registered_method=True)
        self.ConsumeBatch = channel.unary_unary(
                '/pelicanq.v1.QueueService/ConsumeBatch',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchResponse.FromString,
                _registered_method=True)
        self.ConsumeStream = channel.stream_stream(
                '/pelicanq.v1.QueueService/ConsumeStream',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeStreamAck.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_message__pb2.ConsumedMessage.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/pelicanq.v1.QueueService/Ack',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.AckRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.AckResponse.FromString,
                _registered_method=True)
        self.Nack = channel.unary_unary(
                '/pelicanq.v1.QueueService/Nack',
                request_serializer=pelicanq_dot_v1_dot_queue__pb2.NackRequest.SerializeToString,
                response_deserializer=pelicanq_dot_v1_dot_queue__pb2.NackResponse.FromString,
                _registered_method=True)


class QueueServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DeclareQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeStream(self, request_iterator, context):
        """Streaming consume: server streams messages to the client as they arrive.
        Client sends ack/nack on the return stream. Implemented in Phase 4 Step 2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Nack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeclareQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareQueue,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.DeclareQueueRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.DeclareQueueResponse.SerializeToString,
            ),
            'ListQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueues,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.ListQueuesRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.ListQueuesResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.PublishRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.PublishResponse.SerializeToString,
            ),
            'PublishBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishBatch,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.PublishBatchRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.PublishBatchResponse.SerializeToString,
            ),
            'Consume': grpc.unary_unary_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeResponse.SerializeToString,
            ),
            'ConsumeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeBatch,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchResponse.SerializeToString,
            ),
            'ConsumeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ConsumeStream,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.ConsumeStreamAck.FromString,
                    response_serializer=pelicanq_dot_v1_dot_message__pb2.ConsumedMessage.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.AckRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.AckResponse.SerializeToString,
            ),
            'Nack': grpc.unary_unary_rpc_method_handler(
                    servicer.Nack,
                    request_deserializer=pelicanq_dot_v1_dot_queue__pb2.NackRequest.FromString,
                    response_serializer=pelicanq_dot_v1_dot_queue__pb2.NackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pelicanq.v1.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pelicanq.v1.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeclareQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/DeclareQueue',
            pelicanq_dot_v1_dot_queue__pb2.DeclareQueueRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.DeclareQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/ListQueues',
            pelicanq_dot_v1_dot_queue__pb2.ListQueuesRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/Publish',
            pelicanq_dot_v1_dot_queue__pb2.PublishRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/PublishBatch',
            pelicanq_dot_v1_dot_queue__pb2.PublishBatchRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.PublishBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/Consume',
            pelicanq_dot_v1_dot_queue__pb2.ConsumeRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/ConsumeBatch',
            pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.ConsumeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pelicanq.v1.QueueService/ConsumeStream',
            pelicanq_dot_v1_dot_queue__pb2.ConsumeStreamAck.SerializeToString,
            pelicanq_dot_v1_dot_message__pb2.ConsumedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/Ack',
            pelicanq_dot_v1_dot_queue__pb2.AckRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Nack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pelicanq.v1.QueueService/Nack',
            pelicanq_dot_v1_dot_queue__pb2.NackRequest.SerializeToString,
            pelicanq_dot_v1_dot_queue__pb2.NackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
